export const LOAD_SHOP_ITEMS__REQUEST = 'LOAD_SHOP_ITEMS__REQUEST'
export const LOAD_SHOP_ITEMS__SUCCESS = 'LOAD_SHOP_ITEMS__SUCCESS'
export const LOAD_SHOP_ITEMS__FAILURE = 'LOAD_SHOP_ITEMS__FAILURE'
export const LOAD_SHOP_ITEMS__CANCEL = 'LOAD_SHOP_ITEMS__CANCEL'

export const ADD_SHOP_ITEM_TO_CART = 'ADD_SHOP_ITEM_TO_CART'
